@url =  https://api-mern-project.herokuapp.com

### Create a video
POST {{url}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t=3061s",
    "title": "mern video",
    "description": "video tutorial"
}

### Get one video
GET {{url}}/videos/5f9afd6be2f6

### Get all videos
GET {{url}}/videos


### Delete a video
DELETE  {{url}}/videos/5f924cb47cc2a665cf6fed2f

### Update a video
PUT {{url}}/videos/5f9afd6ce73cc25da3dbe2f6
Content-Type: application/json

{
    "title": "mern Tutorial video 2",
    "description": "video tutorial new 2"
}